"""migration

Revision ID: 45ea4df05a3d
Revises: 
Create Date: 2025-05-26 23:24:57.269960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ea4df05a3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_user_id'], ['id'])
        batch_op.drop_column('assigned_user')

    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_user_id'], ['id'])
        batch_op.drop_column('assigned_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_user_id')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_user_id')

    # ### end Alembic commands ###
